feat: docker-compose 추가

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -72,6 +72,15 @@ jobs:
             echo "No tagged images (other than latest) to delete"
           fi
 
+      - name: docker-compose.yml 파일을 EC2로 전송하기
+        uses: appleboy/scp-action@v0.1.3
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.EC2_PRIVATE_KEY }}
+          source: "./docker-compose.yml"
+          target: "/home/ubuntu/docker-compose.yml"
+
       - name: SSH로 EC2에 접속하기
         uses: appleboy/ssh-action@v1.0.3
         with:
@@ -80,10 +89,26 @@ jobs:
           key: ${{ secrets.EC2_PRIVATE_KEY }}
           script_stop: true
           script: |
+            if ! command -v docker-compose &> /dev/null
+            then
+            echo "docker-compose could not be found, installing..."
+            sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+            sudo chmod +x /usr/local/bin/docker-compose
+            fi
+            
             docker stop dreamketcher-dev-server || true
             docker rm dreamketcher-dev-server || true
             
             docker system prune -af || true
             
-            docker pull ${{ steps.login-ecr.outputs.registry }}/dreamketcher-dev-server:latest
-            docker run -d --name dreamketcher-dev-server -p 8080:8080 -e SPRING_PROFILES_ACTIVE=dev -e JASYPT_ENCRYPTOR_PASSWORD=${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }} ${{ steps.login-ecr.outputs.registry }}/dreamketcher-dev-server:latest
+            echo "ECR_URL=${{ steps.login-ecr.outputs.registry }}" > /home/ubuntu/.env
+            echo "JASYPT_ENCRYPTOR_PASSWORD=${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}" >> /home/ubuntu/.env
+            echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> /home/ubuntu/.env
+            
+            cd /home/ubuntu
+            docker-compose --env-file .env up -d --build --pull
+            
+            docker ps
+
+#            docker pull ${{ steps.login-ecr.outputs.registry }}/dreamketcher-dev-server:latest
+#            docker run -d --name dreamketcher-dev-server -p 8080:8080 -e SPRING_PROFILES_ACTIVE=dev -e JASYPT_ENCRYPTOR_PASSWORD=${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }} ${{ steps.login-ecr.outputs.registry }}/dreamketcher-dev-server:latest
